source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TableSectionModules_Example', :exclusive => true do
  pod "TableSectionModules", :path => "../"
end

target 'TableSectionModules_Tests', :exclusive => true do
  pod "TableSectionModules", :path => "../"

  
end
